<?php
$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <style>
        body { padding-top: 60px; }
        .app { display: flex; min-height: 100vh; flex-direction: column; }
        .app-content { flex: 1; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?=(isset($pageView))?$this->displayArea($pageView['area']->getArea('logo_area')):null;?>
                </div>
                <?=(isset($pageView))?$this->displayArea($pageView['area']->getArea('menu_main')):null;?>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?php echo $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
            <?=(isset($pageView))?$this->displayArea($pageView['area']->getArea('footer')):null;?>
    </footer>
<script>
    window.onbeforeunload = function (e) {
        console.log(e);
    }
</script>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
