<?php
$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <link href="/assets/styles/mode-edit.css" media="screen" rel="stylesheet" type="text/css">
    <script type="text/javascript">
        if (document.addEventListener) { // IE >= 9; other browsers
            document.addEventListener('contextmenu', function(e) {
                e.preventDefault();

                e = e || window.event;
                var target = e.target || e.srcElement,
                    text = target.textContent || text.innerText;

                var clickedElement = e.args;
                console.log(text);
                // var id = clickedElement.id;

                if(document.getElementsByClassName('context-menu').length>0) {
                    document.getElementsByClassName('context-menu').remove();
                }

                var div = document.createElement("div");//.setAttribute('style','position:absolute;top:'+getMouseY()+';left:'+getMouseX()+';');
                var t = document.createTextNode("Edit Content");

                var list = document.createElement('ul');
                // Edit Content
                var listItemEditContent = document.createElement('li');
                var linkItemEditContent = document.createElement('a');
                linkItemEditContent.setAttribute('href','#');
                linkItemEditContent.setAttribute('onclick','javascript:return false;');
                linkItemEditContent.appendChild(document.createTextNode("Edit Content"));
                listItemEditContent.appendChild(linkItemEditContent);
                list.appendChild(listItemEditContent);
                // Edit Block
                var listItemEditBlock = document.createElement('li');
                var linkItemEditBlock = document.createElement('a');
                linkItemEditBlock.setAttribute('href','#');
                linkItemEditBlock.setAttribute('onclick','javascript:return false;');
                linkItemEditBlock.appendChild(document.createTextNode("Edit Block"));
                listItemEditBlock.appendChild(linkItemEditBlock);
                list.appendChild(listItemEditBlock);
                // Edit Area
                var listItemEditArea = document.createElement('li');
                var linkItemEditArea = document.createElement('a');
                linkItemEditArea.setAttribute('href','#');
                linkItemEditArea.setAttribute('onclick','javascript:return false;');
                linkItemEditArea.appendChild(document.createTextNode("Edit Area"));
                listItemEditArea.appendChild(linkItemEditArea);
                list.appendChild(listItemEditArea);

                div.appendChild(list);
                div.setAttribute('style','position:absolute;top:'+getMouseY()+'px;left:'+getMouseX()+'px;');
                div.setAttribute('class','context-menu');

                document.body.appendChild(div);
            }, false);

            console.log(getMouseX());

        } else { // IE < 9
            document.attachEvent('oncontextmenu', function() {
                alert("You've tried to open context menu");
                window.event.returnValue = false;
            });
        }
        var x = null;
        var y = null;

        document.addEventListener('mousemove', onMouseUpdate, false);
        document.addEventListener('mouseenter', onMouseUpdate, false);
        // document.addEventListener('oncontextmenu', onMouseUpdate, false);

        function position(){

        }
        function onMouseUpdate(e) {
            x = e.pageX;
            y = e.pageY;
        }

        function getMouseX() {
            return x;
        }

        function getMouseY() {
            return y;
        }


        Element.prototype.remove = function() {
            this.parentElement.removeChild(this);
        }
        NodeList.prototype.remove = HTMLCollection.prototype.remove = function() {
            for(var i = this.length - 1; i >= 0; i--) {
                if(this[i] && this[i].parentElement) {
                    this[i].parentElement.removeChild(this[i]);
                }
            }
        }

    </script>
    <style>
        body { padding-top: 60px; }
        .app { display: flex; min-height: 100vh; flex-direction: column; }
        .app-content { flex: 1; }
        .app-footer { padding-bottom: 1em; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?=(isset($pageView))?$this->displayArea($pageView->getVariable('area')->getArea('logo_area')):null;?>
                </div>
                <?=(isset($pageView))?$this->displayArea($pageView->getVariable('area')->getArea('menu_main')):null;?>
            </div>
        </nav>
    </header>
    <div class="app-content">
        <main class="container">
            <?php echo $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
            <?=(isset($pageView))?$this->displayArea($pageView->getVariable('area')->getArea('footer')):null;?>
    </footer>
<script>
    window.onbeforeunload = function (e) {
        console.log(e);
    }
</script>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
