<?php

// Inlcude common Styles
$this->headLink() ->prependStylesheet('/assets/styles/styles.min.css');
$this->headLink() ->prependStylesheet('/assets/styles/common.min.css');

$this->inlineScript()->prependFile('/assets/scripts/modules.min.js');
$this->inlineScript()->appendFile('/assets/scripts/common.min.js');

if(null!==$this->hasIdentity()) {
    $this->inlineScript()
        ->appendFile('/assets/scripts/editor.min.js')
    ;
    $this->headLink()
        ->appendStylesheet('/assets/styles/editor.min.css')
    ;
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>

    <style>
        body { padding-top: 60px; }
        .app { display: flex; min-height: 100vh; flex-direction: column; }
        .app-content { flex: 1; }
        .app-footer { padding-bottom: 1em; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?=(isset($pageView)&&null!==$pageView->getVariable('area'))?$this->displayArea($pageView->getVariable('area')->getArea('logo_area')):null;?>
                </div>
                <?=(isset($pageView)&&null!==$pageView->getVariable('area'))?$this->displayArea($pageView->getVariable('area')->getArea('menu_main')):null;?>
            </div>
        </nav>
    </header>
    <div class="app-content">
        <main class="container">
            <?php echo $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <?=(null!==$this->hasIdentity() && null!==$pageView  && false!==$this->hasIdentity())?"<a href='".$this->url('page.edit',['uid'=>$pageView->getVariable('page')->getRoute()])."'>Edit this page</a>":''; ?>
        <?=(isset($pageView)&&null!==$pageView->getVariable('area'))?$this->displayArea($pageView->getVariable('area')->getArea('footer')):null;?>
    </footer>

    <?php echo $this->partial('messenger::chat_window', array(
        'from' => 'Team Framework',
        'subject' => 'view partials')); ?>

<?php if(null!==$this->hasIdentity() && false!==$this->hasIdentity()):?>
    <div class="modal fade" id="updateModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body&hellip;</p>
                    <textarea class="summernote"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
<?php endif;?>
    <?php
//    $this->mainMenu()->setItems([
//        [
//            'id' => 'home',
//            'label' => 'Home',
//            'link' => $this->url('home')
//        ],
//        [
//            'id' => 'downloads',
//            'label' => 'Downloads',
//            'link' => $this->url("application", ['action'=>'downloads'])
//        ],
//        [
//            'id' => 'support',
//            'label' => 'Support',
//            'dropdown' => [
//                [
//                    'id' => 'documentation',
//                    'label' => 'Documentation',
//                    'link' => $this->url('doc', ['page'=>'contents'])
//                ],
//                [
//                    'id' => 'help',
//                    'label' => 'Help',
//                    'link' => $this->url('static', ['page'=>'help'])
//                ]
//            ]
//        ],
//        [
//            'id' => 'about',
//            'label' => 'About',
//            'link' => $this->url('about')
//        ],
//    ]);

//    echo $this->mainMenu()->render();
    ?>
    <?php echo $this->inlineScript(); ?>
<script>
    var chat = new Chat('chat');
<?php if(null!==$this->hasIdentity() && false!==$this->hasIdentity()):?>
    chat.setIdentity('<?=$this->getIdentity();?>');
<?php endif; ?>
    window.onbeforeunload = function (e) {
        console.log(e);
    }
    $(document).ready(function() {
        //$('.summernote').summernote();
    });
</script>



</body>
</html>
