<div class="chat-enable chat-minimized" id="chat-wrapper">
    <div id="chat-tab">
        <h4>
            <span>Chat</span>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        </h4>
    </div>
    <div id="chat-content">
        <div id="chat-history">
            <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate pull-right"></span>
        </div>
        <hr />
        <input id="chat-text" type="text" />
        <input id="chat-submit-btn" class="btn-submit btn btn-default" type="submit" value="Send" />
    </div>
</div>