<div class="container">
    <?php if(array_key_exists('content_header',$area)): ?>
    <div class="content-header" data-area-identifier="area-content_header">
        <?=$this->partial('content/area', array(
            'area' => $area['content_header'],
        ));?>
    </div><!-- /.content-header -->
    <?php endif; ?>
    <?php if(array_key_exists('content_main',$area)): ?>
    <div class="row">
        <div class="col-sm-12 content-main content-full" data-area-identifier="area-content_main">
            <?=$this->partial('content/area', array(
                'area' => $area['content_main'],
            ));?>
        </div>
    </div>
    <?php endif; ?>
</div><!-- /.container -->
<?php if(array_key_exists('footer_main',$area)): ?>
    <footer class="content-footer footer-main" data-area-identifier="area-footer_main">
        <?=$this->partial('content/area', array(
            'area' => $area['footer_main'],
        ));?>
    </footer>
<?php endif; ?>
