<h2>User List</h2>

<a href="<?=$this->url('user.create')?>">Create User</a>
<table>
<?php foreach($pageData as $item):?>
    <tr>
        <td>
            <?=$item->getUid();?>
        </td>
        <td>
            <?=$item->getEmail();?>
        </td>
        <td>
            <a href="<?=$this->url('user.create',['uid'=>$item->getUid()]);?>" class="btn btn-default">Details</a>
        </td>
    </tr>
<?php endforeach;?>
</table>
